### ISSUE TITLE
Build process failed on arch linux

### ISSUE THREAD

**Issue by renaldofreire** [gardner/jellyfin-tizen-build#3]
**What I did:**

1. Cloned the repository: `git clone jellyfin-tizen-build`
2. I entered the downloaded directory: `cd jellyfin-tizen-build`
3. I ran the commands suggested in the README.me, one at a time.

**Result:**
After running the commands, an empty directory `output/` is created without the binary file.

**What is my OS:**
- OS: Arch Linux x86_64
- GNOME 41.5
- Kernel: 5.15.31-1-lts
- Docker version 20.10.14

Could you suggest something that might solve this problem?

**Comment by anon059** [comment]
one guy has same issue on reddit page, try chmod 777 output folder and run "docker run -v "$(pwd)/output":/output -it jellyfin-tizen-build" again

**Comment by renaldofreire** [comment]
Thanks, that solved the problem!
