### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by Ard3ny** [gardner/jellyfin-tizen-build#7]
Hi,

I've run just the first command and it fails.
My docker version: 24.0.6
      
Here is a log.

`docker build --ulimit nofile=65536:65536 --progress=plain --no-cache -t jellyfin-tizen-build .
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 1.76kB done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 transferring context: 2B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/node:18
#3 DONE 1.4s

#4 [internal] load metadata for docker.io/library/eclipse-temurin:11
#4 DONE 1.4s

#5 [stage-1 1/7] FROM docker.io/library/eclipse-temurin:11@sha256:f05c8dfa25aa75d994e48c54eef6be4c05326627c066f67497fb4a86f545ec4a
#5 resolve docker.io/library/eclipse-temurin:11@sha256:f05c8dfa25aa75d994e48c54eef6be4c05326627c066f67497fb4a86f545ec4a 0.0s done
#5 ...

#6 [internal] load build context
#6 transferring context: 1.33kB done
#6 DONE 0.0s

#5 [stage-1 1/7] FROM docker.io/library/eclipse-temurin:11@sha256:f05c8dfa25aa75d994e48c54eef6be4c05326627c066f67497fb4a86f545ec4a
#5 sha256:9c9b84d4f83e9433294f1153fc591b4eaceb91b95bb513b4fb9a414f99a73f49 6.79kB / 6.79kB done
#5 sha256:f05c8dfa25aa75d994e48c54eef6be4c05326627c066f67497fb4a86f545ec4a 1.70kB / 1.70kB done
#5 sha256:1584fd589b45a67b6f56b0c702776ca3d5640d1001f7848f5bcd19cb10545eaa 1.37kB / 1.37kB done
#5 sha256:39769250f2be0be25f38285d2996eb4dcbdfaddd7ad6c025b98e2fc2d955a973 0B / 12.90MB 2.3s
#5 sha256:39769250f2be0be25f38285d2996eb4dcbdfaddd7ad6c025b98e2fc2d955a973 2.10MB / 12.90MB 2.5s
#5 sha256:39769250f2be0be25f38285d2996eb4dcbdfaddd7ad6c025b98e2fc2d955a973 7.34MB / 12.90MB 2.6s
#5 sha256:39769250f2be0be25f38285d2996eb4dcbdfaddd7ad6c025b98e2fc2d955a973 12.90MB / 12.90MB 2.7s
#5 extracting sha256:39769250f2be0be25f38285d2996eb4dcbdfaddd7ad6c025b98e2fc2d955a973
#5 sha256:39769250f2be0be25f38285d2996eb4dcbdfaddd7ad6c025b98e2fc2d955a973 12.90MB / 12.90MB 3.3s done
#5 sha256:7d78bd96cc6f3e32688badf91f63c46e109ee5d0b1f6089aa9c94cdc502835ac 0B / 144.84MB 3.4s
#5 sha256:609b859ad36b156f56ea6def0bc711287fa37701f140011a062fffe1e9f5c076 0B / 176B 3.4s
#5 sha256:7d78bd96cc6f3e32688badf91f63c46e109ee5d0b1f6089aa9c94cdc502835ac 10.49MB / 144.84MB 3.7s
#5 sha256:609b859ad36b156f56ea6def0bc711287fa37701f140011a062fffe1e9f5c076 176B / 176B 3.6s done
#5 sha256:442b4ebcd69d88fb1111ee21247fca359f46b4a4c455e6ce4ff6a05974ff72da 0B / 734B 3.7s
#5 extracting sha256:39769250f2be0be25f38285d2996eb4dcbdfaddd7ad6c025b98e2fc2d955a973 0.7s done
#5 sha256:7d78bd96cc6f3e32688badf91f63c46e109ee5d0b1f6089aa9c94cdc502835ac 25.17MB / 144.84MB 4.0s
#5 sha256:442b4ebcd69d88fb1111ee21247fca359f46b4a4c455e6ce4ff6a05974ff72da 734B / 734B 3.8s done
#5 sha256:7d78bd96cc6f3e32688badf91f63c46e109ee5d0b1f6089aa9c94cdc502835ac 36.70MB / 144.84MB 4.2s
#5 sha256:7d78bd96cc6f3e32688badf91f63c46e109ee5d0b1f6089aa9c94cdc502835ac 52.43MB / 144.84MB 4.5s
#5 sha256:7d78bd96cc6f3e32688badf91f63c46e109ee5d0b1f6089aa9c94cdc502835ac 65.01MB / 144.84MB 4.7s
#5 sha256:7d78bd96cc6f3e32688badf91f63c46e109ee5d0b1f6089aa9c94cdc502835ac 78.64MB / 144.84MB 4.9s
#5 sha256:7d78bd96cc6f3e32688badf91f63c46e109ee5d0b1f6089aa9c94cdc502835ac 89.13MB / 144.84MB 5.1s
#5 sha256:7d78bd96cc6f3e32688badf91f63c46e109ee5d0b1f6089aa9c94cdc502835ac 99.61MB / 144.84MB 5.3s
#5 sha256:7d78bd96cc6f3e32688badf91f63c46e109ee5d0b1f6089aa9c94cdc502835ac 110.10MB / 144.84MB 5.5s
#5 sha256:7d78bd96cc6f3e32688badf91f63c46e109ee5d0b1f6089aa9c94cdc502835ac 131.07MB / 144.84MB 5.8s
#5 sha256:7d78bd96cc6f3e32688badf91f63c46e109ee5d0b1f6089aa9c94cdc502835ac 139.46MB / 144.84MB 5.9s
#5 ...

#7 [stage-0 1/3] FROM docker.io/library/node:18@sha256:cd7fa8f136023f7500490e410ba70dd3982ccca21805264f2a260a3a97be7376
#7 resolve docker.io/library/node:18@sha256:cd7fa8f136023f7500490e410ba70dd3982ccca21805264f2a260a3a97be7376 0.0s done
#7 sha256:eb0c3fe14562eb135fb154841d61e28816371e6bac30b059e6f6aabd356b6c6c 2.00kB / 2.00kB done
#7 sha256:cf58080ad70c11059df1bcd3eafe1bb93c49403d434d4a4649e0f7dc4f562f5a 7.29kB / 7.29kB done
#7 sha256:0a9573503463fd3166b5b1f34a7720dac28609e98d731e50e7068f92e79b8545 49.58MB / 49.58MB 1.3s done
#7 sha256:1ccc26d841b4acc2562483bf393ce1cf8bc358ced09ccd825425226827c79c92 24.05MB / 24.05MB 1.1s done
#7 sha256:800d84653581fc119cd75cd572fa190d3b813d49221b9e5ee463e3560e2cb342 64.13MB / 64.13MB 1.8s done
#7 sha256:cd7fa8f136023f7500490e410ba70dd3982ccca21805264f2a260a3a97be7376 1.21kB / 1.21kB done
#7 sha256:7c632e57ea62ea950c367f484f52cdcfd2adb12060a31f5c413f40db9822e96e 211.06MB / 211.06MB 8.0s done
#7 extracting sha256:0a9573503463fd3166b5b1f34a7720dac28609e98d731e50e7068f92e79b8545 1.3s done
#7 sha256:cfd71c20c2b41f8ad03773da65aaebd2fd58ba65cff6a52a1f0c414b34003503 3.37kB / 3.37kB 1.5s done
#7 sha256:d56b98df89209bd41dd8108f225481af35b6b5bdd3542a4f7b61b219b2b6486a 45.92MB / 45.92MB 3.2s done
#7 sha256:69811a7fc2cfe2f28c8c6f4572f82fbb22a3c5aa4897f270a14653a3e43d32b6 2.28MB / 2.28MB 2.0s done
#7 sha256:14a6d9f69108761ebfb9eaa33f567d54830201eb9ad4fbfc4772e07ce37a7c0a 451B / 451B 2.2s done
#7 extracting sha256:1ccc26d841b4acc2562483bf393ce1cf8bc358ced09ccd825425226827c79c92 0.5s done
#7 extracting sha256:800d84653581fc119cd75cd572fa190d3b813d49221b9e5ee463e3560e2cb342 1.7s done
#7 extracting sha256:7c632e57ea62ea950c367f484f52cdcfd2adb12060a31f5c413f40db9822e96e 1.9s
#7 ...

#5 [stage-1 1/7] FROM docker.io/library/eclipse-temurin:11@sha256:f05c8dfa25aa75d994e48c54eef6be4c05326627c066f67497fb4a86f545ec4a
#5 sha256:7d78bd96cc6f3e32688badf91f63c46e109ee5d0b1f6089aa9c94cdc502835ac 144.84MB / 144.84MB 10.7s done
#5 extracting sha256:7d78bd96cc6f3e32688badf91f63c46e109ee5d0b1f6089aa9c94cdc502835ac
#5 extracting sha256:7d78bd96cc6f3e32688badf91f63c46e109ee5d0b1f6089aa9c94cdc502835ac 1.5s done
#5 extracting sha256:609b859ad36b156f56ea6def0bc711287fa37701f140011a062fffe1e9f5c076 done
#5 extracting sha256:442b4ebcd69d88fb1111ee21247fca359f46b4a4c455e6ce4ff6a05974ff72da done
#5 DONE 14.5s

#8 [stage-1 2/7] WORKDIR /tizen
#8 DONE 4.5s

#7 [stage-0 1/3] FROM docker.io/library/node:18@sha256:cd7fa8f136023f7500490e410ba70dd3982ccca21805264f2a260a3a97be7376
#7 extracting sha256:7c632e57ea62ea950c367f484f52cdcfd2adb12060a31f5c413f40db9822e96e 4.1s done
#7 extracting sha256:cfd71c20c2b41f8ad03773da65aaebd2fd58ba65cff6a52a1f0c414b34003503 done
#7 extracting sha256:d56b98df89209bd41dd8108f225481af35b6b5bdd3542a4f7b61b219b2b6486a 1.6s done
#7 extracting sha256:69811a7fc2cfe2f28c8c6f4572f82fbb22a3c5aa4897f270a14653a3e43d32b6 0.0s done
#7 extracting sha256:14a6d9f69108761ebfb9eaa33f567d54830201eb9ad4fbfc4772e07ce37a7c0a done
#7 DONE 19.1s

#9 [stage-0 2/3] WORKDIR /jellyfin
#9 DONE 0.0s

#10 [stage-0 3/3] RUN curl -sL https://github.com/jellyfin/jellyfin-web/archive/refs/heads/master.tar.gz | tar -xz &&     mv jellyfin-web-master jellyfin-web &&     cd jellyfin-web &&     npx browserslist@latest --update-db &&     SKIP_PREPARE=1 npm ci --no-audit &&     npm run build:production &&     cd .. &&     curl -sL https://github.com/jellyfin/jellyfin-tizen/archive/refs/heads/master.tar.gz | tar -xz &&     mv jellyfin-tizen-master jellyfin-tizen &&     cd jellyfin-tizen &&     JELLYFIN_WEB_DIR=../jellyfin-web/dist npm ci --no-audit
#10 2.146 npm WARN exec The following package was not found and will be installed: browserslist@4.22.1
#10 3.320 The --update-db command is deprecated.
#10 3.320 Please use npx update-browserslist-db@latest instead.
#10 3.320 Browserslist DB update will still be made.
#10 4.065 Latest version:     1.0.30001549
#10 4.098 Installed version:  1.0.30001480
#10 4.098 Removing old caniuse-lite from lock file
#10 4.103 Installing new caniuse-lite version
#10 4.103 $ npm install caniuse-lite
#10 5.104 npm ERR! code EBADENGINE
#10 5.104 npm ERR! engine Unsupported engine
#10 5.104 npm ERR! engine Not compatible with your version of node/npm: jellyfin-web@10.9.0
#10 5.104 npm ERR! notsup Not compatible with your version of node/npm: jellyfin-web@10.9.0
#10 5.104 npm ERR! notsup Required: {"node":">=20.0.0","npm":">=9.6.4","yarn":"YARN NO LONGER USED - use npm instead."}
#10 5.104 npm ERR! notsup Actual:   {"npm":"9.8.1","node":"v18.18.1"}
#10 5.104
#10 5.104 npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-10-14T10_34_08_227Z-debug-0.log
#10 5.104
#10 5.104 Error: Command failed: npm install caniuse-lite
#10 5.104 npm ERR! code EBADENGINE
#10 5.104 npm ERR! engine Unsupported engine
#10 5.104 npm ERR! engine Not compatible with your version of node/npm: jellyfin-web@10.9.0
#10 5.104 npm ERR! notsup Not compatible with your version of node/npm: jellyfin-web@10.9.0
#10 5.104 npm ERR! notsup Required: {"node":">=20.0.0","npm":">=9.6.4","yarn":"YARN NO LONGER USED - use npm instead."}
#10 5.104 npm ERR! notsup Actual:   {"npm":"9.8.1","node":"v18.18.1"}
#10 5.104
#10 5.104 npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-10-14T10_34_08_227Z-debug-0.log
#10 5.104
#10 5.104     at checkExecSyncError (node:child_process:890:11)
#10 5.104     at execSync (node:child_process:962:15)
#10 5.104     at updatePackageManually (/root/.npm/_npx/072487b38308305a/node_modules/update-browserslist-db/index.js:219:5)
#10 5.104     at updateDB (/root/.npm/_npx/072487b38308305a/node_modules/update-browserslist-db/index.js:289:5)
#10 5.104     at Object.<anonymous> (/root/.npm/_npx/072487b38308305a/node_modules/browserslist/cli.js:47:3)
#10 5.104     at Module._compile (node:internal/modules/cjs/loader:1256:14)
#10 5.104     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
#10 5.104     at Module.load (node:internal/modules/cjs/loader:1119:32)
#10 5.104     at Module._load (node:internal/modules/cjs/loader:960:12)
#10 5.104
#10 5.104 Problem with `npm install caniuse-lite` call. Run it manually.
#10 5.109 npm notice
#10 5.109 npm notice New major version of npm available! 9.8.1 -> 10.2.0
#10 5.109 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.2.0>
#10 5.109 npm notice Run `npm install -g npm@10.2.0` to update!
#10 5.109 npm notice
#10 ERROR: process "/bin/sh -c curl -sL ${JELLYFIN_WEB_URL} | tar -xz &&     mv jellyfin-web-master jellyfin-web &&     cd jellyfin-web &&     npx browserslist@latest --update-db &&     SKIP_PREPARE=1 npm ci --no-audit &&     npm run build:production &&     cd .. &&     curl -sL ${JELLYFIN_TIZEN_URL} | tar -xz &&     mv jellyfin-tizen-master jellyfin-tizen &&     cd jellyfin-tizen &&     JELLYFIN_WEB_DIR=../jellyfin-web/dist npm ci --no-audit" did not complete successfully: exit code: 1
------
 > [stage-0 3/3] RUN curl -sL https://github.com/jellyfin/jellyfin-web/archive/refs/heads/master.tar.gz | tar -xz &&     mv jellyfin-web-master jellyfin-web &&     cd jellyfin-web &&     npx browserslist@latest --update-db &&     SKIP_PREPARE=1 npm ci --no-audit &&     npm run build:production &&     cd .. &&     curl -sL https://github.com/jellyfin/jellyfin-tizen/archive/refs/heads/master.tar.gz | tar -xz &&     mv jellyfin-tizen-master jellyfin-tizen &&     cd jellyfin-tizen &&     JELLYFIN_WEB_DIR=../jellyfin-web/dist npm ci --no-audit:
5.104     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
5.104     at Module.load (node:internal/modules/cjs/loader:1119:32)
5.104     at Module._load (node:internal/modules/cjs/loader:960:12)
5.104
5.104 Problem with `npm install caniuse-lite` call. Run it manually.
5.109 npm notice
5.109 npm notice New major version of npm available! 9.8.1 -> 10.2.0
5.109 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.2.0>
5.109 npm notice Run `npm install -g npm@10.2.0` to update!
5.109 npm notice
------
Dockerfile:9
--------------------
   8 |
   9 | >>> RUN curl -sL ${JELLYFIN_WEB_URL} | tar -xz && \
  10 | >>>     mv jellyfin-web-master jellyfin-web && \
  11 | >>>     cd jellyfin-web && \
  12 | >>>     npx browserslist@latest --update-db && \
  13 | >>>     SKIP_PREPARE=1 npm ci --no-audit && \
  14 | >>>     npm run build:production && \
  15 | >>>     cd .. && \
  16 | >>>     curl -sL ${JELLYFIN_TIZEN_URL} | tar -xz && \
  17 | >>>     mv jellyfin-tizen-master jellyfin-tizen && \
  18 | >>>     cd jellyfin-tizen && \
  19 | >>>     JELLYFIN_WEB_DIR=../jellyfin-web/dist npm ci --no-audit
  20 |
--------------------
ERROR: failed to solve: process "/bin/sh -c curl -sL ${JELLYFIN_WEB_URL} | tar -xz &&     mv jellyfin-web-master jellyfin-web &&     cd jellyfin-web &&     npx browserslist@latest --update-db &&     SKIP_PREPARE=1 npm ci --no-audit &&     npm run build:production &&     cd .. &&     curl -sL ${JELLYFIN_TIZEN_URL} | tar -xz &&     mv jellyfin-tizen-master jellyfin-tizen &&     cd jellyfin-tizen &&     JELLYFIN_WEB_DIR=../jellyfin-web/dist npm ci --no-audit" did not complete successfully: exit code: 1`

**Comment by gardner** [comment]
Thanks for the report. The container has been updated to use `node` v20 and is now building. Please let me know if this needs to be reopened.
